[theme]
path = "~/.config/yazi/theme.toml"

[manager]
show_hidden = true

[plugin]
prepend_fetchers = [
    { id   = "git", name = "*", run  = "git" },
    { id   = "git", name = "*/", run = "git" }
]

prepend_previewers = [
    { name = "*.md", run = "mdcat" },
    { name = "*.csv", run = "rich-preview"},
    { name = "*.rst", run = "rich-preview"},
    { name = "*.ipynb", run = "rich-preview"},
    { name = "*.json", run = "rich-preview"}
]
