[mgr]
show_hidden = true

[plugin]
prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" }
]

prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false }
]

prepend_previewers = [
    { url = "*.md", run = "rich-preview" },
    { url = "*.csv", run = "duckdb" },
    { url = "*.tsv", run = "duckdb" },
    { url = "*.json", run = "rich-preview" },
    { url = "*.xlsx", run = "duckdb" },
    { url = "*.ipynb", run = "nbpreview" },
]

append_previewers = [
  { url = "*", run = "hexyl" },
]
